// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARoeOh7p8TeFGG9WT_G683mHd8GbtXaXM',
    appId: '1:750990775732:android:430c6353ad8825cac54ee1',
    messagingSenderId: '750990775732',
    projectId: 'serplet-8aa23',
    databaseURL: 'https://serplet-8aa23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'serplet-8aa23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb4UOJEogukPA-FgwN3jdQDS6O5A9xjcw',
    appId: '1:750990775732:ios:42cfcffcdcb966acc54ee1',
    messagingSenderId: '750990775732',
    projectId: 'serplet-8aa23',
    databaseURL: 'https://serplet-8aa23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'serplet-8aa23.appspot.com',
    androidClientId: '750990775732-vc06v3s37mlidb8105vs4eauqpgks31r.apps.googleusercontent.com',
    iosClientId: '750990775732-a14gc1b0frccodnfelg0b07pm5irkpn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.myduit',
  );
}
